- name: SYSTEM POSTGRESQL Official PostgreSQL repository key must be present
  apt_key: url={{ postgresql_key }} state=present

- name: SYSTEM POSTGRESQL Official PostgreSQL repository must be present
  apt_repository: repo={{ postgresql_repository }} state=present update_cache='yes'

- name: SYSTEM POSTGRESQL PostgreSQL is installed
  apt: pkg=postgresql-{{ postgresql_version }} state=present update_cache='yes'
  notify: "POSTGRESQL Restart PostgreSQL Service"
